---
driver:
  name: vagrant
  network:
  - ["forwarded_port", {guest: 80, host: 8080}]
  - ["forwarded_port", {guest: 443, host: 8443}]

provisioner:
  name: chef_solo
  require_chef_omnibus: 12.17.44

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[polignu::default]
    attributes: {
        server_name : "localhost",
        ssl_public_port : "8443"
    }
    
