# Cookbook Name:: polignu
# __Attribute::__server__
#
# Copyright (C) 2016 Diego Rabatone Oliveira.
#
# This file is part of PoliGNU SiteDeploy project.
#
# SiteDeploy is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.

# SiteDeploy is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# PoliGNU SiteDeploy project.  If not, see <http://www.gnu.org/licenses/>.

# This file is dedicated to general nginx configuration attributes
# The attributes below were listed based, firstly, on the nginx.conf.erb file.

# If true, then nginx user will be www-data, otherwise, we will use the
# node["linux_user"] defined at default.rb. Using www-data may cause some
# permission errors while accessing files.
default["nginx"]["user_wwwdata"] = false
default["nginx"]["pid_file"] = "/var/run/nginx.pid"
# For nginx above 1.3.8 this is automatically generated by nginx
default["nginx"]["worker_processes"] = nil
default["nginx"]["worker_rlimit_nofile"] = 2048
default["nginx"]["worker_connections"] = 1024
default["nginx"]["source"]["modules"] = ["nginx::http_gzip_static_module"]
default["nginx"]["resolver"] = "8.8.8.8"
default["nginx"]["php_backend"] = "hhvm" # "php-fpm" is an alternative
default["nginx"]["php_backend_type"] = "unix" # "tcp" is an alternative
