---
driver:
  name: vagrant
  network:
  - ["forwarded_port", {guest: 80, host: 80}]
  - ["forwarded_port", {guest: 443, host: 443}]

provisioner:
  name: chef_solo
  require_chef_omnibus: 12.17.44

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[polignu::default]
    attributes: {
        environment : "local",
        linux_user : "vagrant",
        server_name : "localhost"
    }

